type SpawnableItemsType = {
  [key: string]: number;
};

export const Planets: SpawnableItemsType = {
  Experimentation: 0,
  Assurance: 1,
  Vow: 2,
  "Company Building": 3,
  March: 4,
  Rend: 5,
  Dine: 6,
  Offense: 7,
  Titan: 8,
};

export const SpawnableItems: SpawnableItemsType = {
  Binoculars: 0,
  Boombox: 1,
  Jetpack: 4,
  Key: 5,
  Lockpicker: 6,
  Apparatice: 7,
  Mapper: 8,
  "Pro-flashlight": 9,
  Shovel: 10,
  "Stun grenade": 11,
  "Extension ladder": 12,
  "TZP-Inhalent": 13,
  "Walkie-talkie": 14,
  "Zap gun": 15,
  "Magic 7 ball": 16,
  Airhorn: 17,
  Bell: 18,
  "Big bolt": 19,
  Bottles: 20,
  Brush: 21,
  Candy: 22,
  "Cash register": 23,
  "Chemical jug": 24,
  "Clown horn": 25,
  "Large axle": 26,
  Teeth: 27,
  "Dust pan": 28,
  "Egg beater": 29,
  "V-Type engine": 30,
  "Golden cup": 31,
  "Fancy lamp": 32,
  Painting: 33,
  "Plastic fish": 34,
  "Laser pointer": 35,
  "Gold bar": 36,
  Hairdryer: 37,
  "Magnifying glass": 38,
  "Metal sheet": 39,
  "Cookie mold pan": 40,
  Mug: 41,
  "Perfume bottle": 42,
  "Old phone": 43,
  "Jar of pickles": 44,
  "Pill bottle": 45,
  Remote: 46,
  Ring: 47,
  "Toy robot": 48,
  "Rubber ducky": 49,
  "Red soda": 50,
  "Steering wheel": 51,
  "Stop sign": 52,
  "Tea kettle": 53,
  "Tooth paste": 54,
  "Toy cube": 55,
  Hive: 56,
  "Radar booster": 57,
  "Yield sign": 58,
};
